<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="http://10.1.200.52:2080/soa-infra/services/default/CustomerTestBiz/CustomerTestBiz.wsdl"/>
      <rootElement name="FindCustomersRs" namespace="http://soa.grupovidanta.com/CustomerTestBiz"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../bpelFindCustomers.wsdl"/>
      <rootElement name="FindCustomersRs" namespace="http://soa.grupovidanta.com/CustomerTestEnt"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON NOV 03 15:01:59 CST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://soa.grupovidanta.com/CustomerTestBiz"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:client="http://xmlns.oracle.com/SOAEnvironmentTest/CustomerTestEnt/bpelFindCustomers"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns3="http://soa.grupovidanta.com/VidantaCommons/CustomerTestEnt"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns2="http://soa.grupovidanta.com/CustomerTestEnt"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://soa.grupovidanta.com/CustomerTestBiz/types"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns1="http://soa.grupovidanta.com/VidantaCommons/CustomerTestBiz"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap12 soap mime tns ns0 xsd ns1 wsdl client ns3 plnk ns2 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns2:FindCustomersRs>
      <xsl:if test="/tns:FindCustomersRs/tns:Success">
        <ns2:Success>
          <xsl:value-of select="/tns:FindCustomersRs/tns:Success"/>
        </ns2:Success>
      </xsl:if>
      <ns2:Customers>
        <xsl:for-each select="/tns:FindCustomersRs/tns:Customers/tns:Customer">
          <ns2:Customer>
            <ns2:BasicInformation>
              <ns2:ID>
                <xsl:value-of select="tns:BasicInformation/tns:ID"/>
              </ns2:ID>
              <ns2:Name>
                <xsl:value-of select="tns:BasicInformation/tns:Name"/>
              </ns2:Name>
              <ns2:LastName>
                <xsl:value-of select="tns:BasicInformation/tns:LastName"/>
              </ns2:LastName>
              <ns2:MiddleName>
                <xsl:value-of select="tns:BasicInformation/tns:MiddleName"/>
              </ns2:MiddleName>
              <ns2:Gender>
                <xsl:value-of select="tns:BasicInformation/tns:Gender"/>
              </ns2:Gender>
              <ns2:Email>
                <xsl:value-of select="tns:BasicInformation/tns:Email"/>
              </ns2:Email>
              <ns2:UserName>
                <xsl:value-of select="tns:BasicInformation/tns:UserName"/>
              </ns2:UserName>
              <ns2:Password>
                <xsl:value-of select="tns:BasicInformation/tns:Password"/>
              </ns2:Password>
              <ns2:BirthDate>
                <xsl:value-of select="tns:BasicInformation/tns:BirthDate"/>
              </ns2:BirthDate>
            </ns2:BasicInformation>
            <ns2:Address>
              <ns2:City>
                <xsl:value-of select="tns:Address/tns:City"/>
              </ns2:City>
              <ns2:State>
                <xsl:value-of select="tns:Address/tns:State"/>
              </ns2:State>
              <ns2:ZipCode>
                <xsl:value-of select="tns:Address/tns:ZipCode"/>
              </ns2:ZipCode>
            </ns2:Address>
            <ns2:CreditCard>
              <ns2:Number>
                <xsl:value-of select="tns:CreditCard/tns:Number"/>
              </ns2:Number>
              <ns2:CVV>
                <xsl:value-of select="tns:CreditCard/tns:CVV"/>
              </ns2:CVV>
              <ns2:ExpirationDate>
                <xsl:value-of select="tns:CreditCard/tns:ExpirationDate"/>
              </ns2:ExpirationDate>
              <ns2:Type>
                <xsl:value-of select="tns:CreditCard/tns:Type"/>
              </ns2:Type>
            </ns2:CreditCard>
            <ns2:AditionalInfo>
              <ns2:Company>
                <xsl:value-of select="tns:AditionalInfo/tns:Company"/>
              </ns2:Company>
              <ns2:Vehicle>
                <xsl:value-of select="tns:AditionalInfo/tns:Vehicle"/>
              </ns2:Vehicle>
              <ns2:TelephoneNumber>
                <xsl:value-of select="tns:AditionalInfo/tns:TelephoneNumber"/>
              </ns2:TelephoneNumber>
            </ns2:AditionalInfo>
            <ns2:Memebership>
              <ns2:MembershipCategory>
                <xsl:value-of select="tns:Memebership/tns:MembershipCategory"/>
              </ns2:MembershipCategory>
              <ns2:LoyaltyPoints>
                <xsl:value-of select="tns:Memebership/tns:LoyaltyPoints"/>
              </ns2:LoyaltyPoints>
            </ns2:Memebership>
          </ns2:Customer>
        </xsl:for-each>
      </ns2:Customers>
      <ns2:Errors>
        <xsl:for-each select="/tns:FindCustomersRs/tns:Errors/ns1:Error">
          <ns3:Error>
            <ns3:ErrorCode>
              <xsl:value-of select="ns1:ErrorCode"/>
            </ns3:ErrorCode>
            <ns3:Description>
              <xsl:value-of select="ns1:Description"/>
            </ns3:Description>
            <ns3:BusinessProcess>
              <xsl:value-of select="ns1:BusinessProcess"/>
            </ns3:BusinessProcess>
            <ns3:FailedService>
              <xsl:value-of select="ns1:FailedService"/>
            </ns3:FailedService>
            <ns3:TimeStamp>
              <xsl:value-of select="ns1:TimeStamp"/>
            </ns3:TimeStamp>
          </ns3:Error>
        </xsl:for-each>
      </ns2:Errors>
    </ns2:FindCustomersRs>
  </xsl:template>
</xsl:stylesheet>
