<?xml version="1.0" encoding="UTF-8"?>
<definitions
    
     targetNamespace="http://soa.grupovidanta.com/CustomerTestTec"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://soa.grupovidanta.com/CustomerTestTec"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    >
    <documentation>
        <abstractWSDL>CustomerTestTec_1.wsdl</abstractWSDL>
    </documentation>
    <types>
        <xsd:schema targetNamespace="http://soa.grupovidanta.com/CustomerTestTec/types" elementFormDefault="qualified">
            <xsd:import schemaLocation="xsd/CustomerTestTec.xsd" namespace="http://soa.grupovidanta.com/CustomerTestTec"/>
        </xsd:schema>
    </types>
    <message name="FindCustomerRq">
        <part name="FindCustomerRq" element="tns:FindCustomerRq"/>
    </message>
    <message name="FindCustomerRs">
        <part name="FindCustomerRs" element="tns:FindCustomerRs"/>
    </message>
    <portType name="CustomerTestTecPort">
        <operation name="FindCustomer">
            <input message="tns:FindCustomerRq"/>
            <output message="tns:FindCustomerRs"/>
        </operation>
    </portType>
    <binding name="CustomerTestTecBinding" type="tns:CustomerTestTecPort">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="FindCustomer">
            <soap12:operation style="document" soapAction="http://soa.grupovidanta.com/CustomerTestTec/FindCustomer"
                 soapActionRequired="false"/>
            <input>
                <soap12:body use="literal" parts="FindCustomerRq"/>
            </input>
            <output>
                <soap12:body use="literal" parts="FindCustomerRs"/>
            </output>
        </operation>
    </binding>
    <binding name="CustomerTestTecPortBinding" type="tns:CustomerTestTecPort">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="FindCustomer">
            <soap:operation style="document" soapAction="FindCustomer"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="CustomerTestTec">
        <port name="CustomerTestTecPort_pt" binding="tns:CustomerTestTecPortBinding">
            <soap:address location="http://10.1.200.52:2080/soa-infra/services/default/CustomerTestTec/CustomerTestTec"/>
        </port>
    </service>
</definitions>
