<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../bpelFindCustomers.wsdl"/>
      <rootElement name="FindCustomersRs" namespace="http://soa.grupovidanta.com/CustomerTestBiz"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../CustomerTestBiz.wsdl"/>
      <rootElement name="FindCustomersRs" namespace="http://soa.grupovidanta.com/CustomerTestBiz"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU OCT 23 15:44:33 CDT 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:client="http://xmlns.oracle.com/SOAEnvironmentTest/CustomerTestBiz/bpelFindCustomers"
                xmlns:ns1="http://soa.grupovidanta.com/CustomerTestBiz"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns2="http://soa.grupovidanta.com/CustomerTestBiz/types"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns0="http://soa.grupovidanta.com/VidantaCommons/CustomerTestBiz"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl wsdl client ns1 plnk xsd ns0 soap12 soap mime ns2 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <ns1:FindCustomersRs>
      <xsl:if test="/ns1:FindCustomersRs/ns1:Success">
        <ns1:Success>
          <xsl:value-of select="/ns1:FindCustomersRs/ns1:Success"/>
        </ns1:Success>
      </xsl:if>
      <xsl:if test="/ns1:FindCustomersRs/ns1:Customers">
        <ns1:Customers>
          <xsl:value-of select="/ns1:FindCustomersRs/ns1:Customers"/>
          <xsl:for-each select="/ns1:FindCustomersRs/ns1:Customers/ns1:Customer">
            <ns1:Customer>
              <xsl:value-of select="."/>
              <ns1:BasicInformation>
                <ns1:ID>
                  <xsl:value-of select="ns1:BasicInformation/ns1:ID"/>
                </ns1:ID>
                <ns1:Name>
                  <xsl:value-of select="ns1:BasicInformation/ns1:Name"/>
                </ns1:Name>
                <ns1:LastName>
                  <xsl:value-of select="ns1:BasicInformation/ns1:LastName"/>
                </ns1:LastName>
                <ns1:MiddleName>
                  <xsl:value-of select="ns1:BasicInformation/ns1:MiddleName"/>
                </ns1:MiddleName>
                <ns1:Gender>
                  <xsl:value-of select="ns1:BasicInformation/ns1:Gender"/>
                </ns1:Gender>
                <ns1:Email>
                  <xsl:value-of select="ns1:BasicInformation/ns1:Email"/>
                </ns1:Email>
                <ns1:UserName>
                  <xsl:value-of select="ns1:BasicInformation/ns1:UserName"/>
                </ns1:UserName>
                <ns1:Password>
                  <xsl:value-of select="ns1:BasicInformation/ns1:Password"/>
                </ns1:Password>
                <ns1:BirthDate>
                  <xsl:value-of select="ns1:BasicInformation/ns1:BirthDate"/>
                </ns1:BirthDate>
              </ns1:BasicInformation>
              <ns1:Address>
                <ns1:City>
                  <xsl:value-of select="ns1:Address/ns1:City"/>
                </ns1:City>
                <ns1:State>
                  <xsl:value-of select="ns1:Address/ns1:State"/>
                </ns1:State>
                <ns1:ZipCode>
                  <xsl:value-of select="ns1:Address/ns1:ZipCode"/>
                </ns1:ZipCode>
              </ns1:Address>
              <ns1:CreditCard>
                <ns1:Number>
                  <xsl:value-of select="ns1:CreditCard/ns1:Number"/>
                </ns1:Number>
                <ns1:CVV>
                  <xsl:value-of select="ns1:CreditCard/ns1:CVV"/>
                </ns1:CVV>
                <ns1:ExpirationDate>
                  <xsl:value-of select="ns1:CreditCard/ns1:ExpirationDate"/>
                </ns1:ExpirationDate>
                <ns1:Type>
                  <xsl:value-of select="ns1:CreditCard/ns1:Type"/>
                </ns1:Type>
              </ns1:CreditCard>
              <ns1:AditionalInfo>
                <ns1:Company>
                  <xsl:value-of select="ns1:AditionalInfo/ns1:Company"/>
                </ns1:Company>
                <ns1:Vehicle>
                  <xsl:value-of select="ns1:AditionalInfo/ns1:Vehicle"/>
                </ns1:Vehicle>
                <ns1:TelephoneNumber>
                  <xsl:value-of select="ns1:AditionalInfo/ns1:TelephoneNumber"/>
                </ns1:TelephoneNumber>
              </ns1:AditionalInfo>
              <ns1:Memebership>
                <ns1:MembershipCategory>
                  <xsl:value-of select="ns1:Memebership/ns1:MembershipCategory"/>
                </ns1:MembershipCategory>
                <ns1:LoyaltyPoints>
                  <xsl:value-of select="ns1:Memebership/ns1:LoyaltyPoints"/>
                </ns1:LoyaltyPoints>
              </ns1:Memebership>
            </ns1:Customer>
          </xsl:for-each>
        </ns1:Customers>
      </xsl:if>
      <xsl:if test="/ns1:FindCustomersRs/ns1:Errors">
        <ns1:Errors>
          <xsl:value-of select="/ns1:FindCustomersRs/ns1:Errors"/>
          <xsl:for-each select="/ns1:FindCustomersRs/ns1:Errors/ns0:Error">
            <ns0:Error>
              <xsl:value-of select="."/>
              <ns0:ErrorCode>
                <xsl:value-of select="ns0:ErrorCode"/>
              </ns0:ErrorCode>
              <ns0:Description>
                <xsl:value-of select="ns0:Description"/>
              </ns0:Description>
              <ns0:BusinessProcess>
                <xsl:value-of select="ns0:BusinessProcess"/>
              </ns0:BusinessProcess>
              <ns0:FailedService>
                <xsl:value-of select="ns0:FailedService"/>
              </ns0:FailedService>
              <ns0:TimeStamp>
                <xsl:value-of select="ns0:TimeStamp"/>
              </ns0:TimeStamp>
            </ns0:Error>
          </xsl:for-each>
        </ns1:Errors>
      </xsl:if>
    </ns1:FindCustomersRs>
  </xsl:template>
</xsl:stylesheet>
