<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../bpelFindReservations.wsdl"/>
      <rootElement name="FindCustomersRs" namespace="http://soa.grupovidanta.com/CustomerTestBiz"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../CustomerTestBiz.wsdl"/>
      <rootElement name="FindCustomersRs" namespace="http://soa.grupovidanta.com/CustomerTestBiz"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [TUE OCT 28 20:50:08 CST 2014]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://soa.grupovidanta.com/CustomerTestBiz"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://soa.grupovidanta.com/CustomerTestBiz/types"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:vid="http://soa.grupovidanta.com/VidantaCommons/CustomerTestBiz"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns xsd vid soap12 soap mime ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <tns:FindCustomersRs>
      <xsl:if test="/tns:FindCustomersRs/tns:Success">
        <tns:Success>
          <xsl:value-of select="/tns:FindCustomersRs/tns:Success"/>
        </tns:Success>
      </xsl:if>
      <xsl:copy-of select="/tns:FindCustomersRs/tns:Customers">
        <?oracle-xsl-mapper-position tns:Customers?>
      </xsl:copy-of>
      <tns:Errors>
        <xsl:for-each select="/tns:FindCustomersRs/tns:Errors/vid:Error">
          <vid:Error>
            <vid:ErrorCode>
              <xsl:value-of select="vid:ErrorCode"/>
            </vid:ErrorCode>
            <vid:Description>
              <xsl:value-of select="vid:Description"/>
            </vid:Description>
            <vid:BusinessProcess>
              <xsl:value-of select="vid:BusinessProcess"/>
            </vid:BusinessProcess>
            <vid:FailedService>
              <xsl:value-of select="vid:FailedService"/>
            </vid:FailedService>
            <vid:TimeStamp>
              <xsl:value-of select="vid:TimeStamp"/>
            </vid:TimeStamp>
          </vid:Error>
        </xsl:for-each>
      </tns:Errors>
    </tns:FindCustomersRs>
  </xsl:template>
</xsl:stylesheet>
