<?binding.jca dbFindCustomers_db.jca?>
<wsdl:definitions name="dbFindCustomers" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAEnvironmentTest/CustomerTestTec/dbFindCustomers" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAEnvironmentTest/CustomerTestTec/dbFindCustomers" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbFindCustomers">
    <plt:partnerLinkType name="dbFindCustomers_plt">
        <plt:role name="dbFindCustomers_role">
            <plt:portType name="tns:dbFindCustomers_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbFindCustomers" schemaLocation="xsd/dbFindCustomers_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="dbFindCustomersSelect_inputParameters">
        <wsdl:part name="dbFindCustomersSelect_inputParameters" element="top:dbFindCustomersSelect_id_name_lastName_userName_emailInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CustomerCollection_msg">
        <wsdl:part name="CustomerCollection" element="top:CustomerCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbFindCustomers_ptt">
        <wsdl:operation name="dbFindCustomersSelect">
            <wsdl:input message="tns:dbFindCustomersSelect_inputParameters"/>
            <wsdl:output message="tns:CustomerCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
